services:
  - type: web
    name: immo-fastapi-service
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: "/health"
    autoDeploy: true
    envVars:
      - key: PORT
        value: "8000"

  - type: web
    name: immo-streamlit-service
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: "/"
    autoDeploy: true
    envVars:
      - key: PORT
        value: "8501"
