services:
  - type: web
    name: immo-code-service
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    healthCheckPath: "/health"
    autoDeploy: true
    envVars:
      - key: PORT
        value: "8000"
