services:
  - type: web
    name: fastapi-service
    env: docker
    dockerfilePath: Dockerfile.fastapi
    plan: free
    healthCheckPath: "/health"
    autoDeploy: true

  - type: web
    name: streamlit-service
    env: docker
    dockerfilePath: Dockerfile.streamlit
    plan: free
    autoDeploy: true
